# Generated by Django 4.2.3 on 2023-07-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('Business', 'Business'), ('Information Technology', 'It'), ('Banking', 'Banking'), ('Education/Training', 'Education'), ('Telecommunication', 'Telecommunication'), ('Creative and Design', 'Design'), ('Others', 'Others')], default='Business', max_length=30),
        ),
    ]
